[package]
name = "skylights-app"
version = "0.1.0"
edition = "2021"
authors = ["retsimx"]
license = "MIT OR Apache-2.0"
description = "ESP32 firmware application for Skylights controller"

[dependencies]
skylights-core = { workspace = true }
esp-hal = { workspace = true }
esp-backtrace = { workspace = true }
esp-println = { workspace = true }
esp-storage = { version = "0.4.0", default-features = false, features = ["esp32", "nor-flash"] }

embedded-storage = { version = "0.3", default-features = false }

